### ISSUE TITLE
leadership_role not updated for 114th Congress

### ISSUE THREAD

**Issue by pqnelson** [sunlightlabs/congress#493]
It seems no one in the house has a `leadership_role` field populated, and only Dick Durbin has that particular field populated in the senate. Alas, he is considered `"Majority Whip"`.

Are there plans to update this feature for the 114th congress?

Will it be populated for older congresses too? (Just curious...)

**Comment by nickom** [comment]
Good catch! That's on me, I meant to update the `leadership_role` field in the [/unitedstates/congress-legislators](https://github.com/unitedstates/congress-legislators) repo last week. I'll get to it tomorrow - apologies for any issues it caused!

As for older congresses, it's not something I was planning on since it's manually done, but I would encourage anyone else with an itch for history and some free time to [start adding older congresses here](https://github.com/unitedstates/congress-legislators/blob/master/legislators-historical.yaml)!

**Comment by nickom** [comment]
Hey Alex,

I've [submitted the changes to the /unitedstates project](https://github.com/unitedstates/congress-legislators/pull/235) and once those are merged you should see it in the API in a couple of hours. I'll let you know when that happens. Thanks again for the nudge!

-Nicko

**Comment by nickom** [comment]
Hi Alex,

My submitted changes were [merged into the /unitedstates project last week](https://github.com/unitedstates/congress-legislators/pull/235) and it looks like they're appearing correctly in our Congress API. I'm going to close this issue since it appears to be resolved, but let me know if you're still having trouble and thanks again for pointing it out!

Best,
Nicko
