### ISSUE TITLE
Roll h12-2016 is not returned by the Votes API

### ISSUE THREAD

**Issue by clozano170** [sunlightlabs/congress#515]
House roll number 12 for 2016 is not found by the Votes API.
https://congress.api.sunlightfoundation.com/votes?roll_id=h12-2016&apikey=[key]

It is listed in the votes fields as part of bill hr712-114:
https://congress.api.sunlightfoundation.com/bills?bill_id=hr712-114&apikey=[key]&fields=votes

Please add h12-2016 to the Votes database, and/or correct the issue with the Votes API.

For reference, see also:
http://clerk.house.gov/evs/2016/roll012.xml
https://www.opencongress.org/bill/hr712-114

**Comment by konklone** [comment]
From looking at `https://congress.api.sunlightfoundation.com/votes?apikey=[key]&fields=roll_id&per_page=50&year=2016` it looks like there are 7 House votes missing -- 7, 8, 9, 10, 11, 12, and 23.

Based on how the votes are ordered in the "natural sort", it looks like the API's underlying crawlers saw votes in bursts which missed those two sets of numbers. Since the scraper grabs 20 at a time, it's possible that votes 7 through 33 were put up all at once, and so the scraper got 13-33 and never got the chance to see 7-12. (This doesn't explain why 23 is missing.)

In any case, re-running [the scraper](https://github.com/sunlightlabs/congress/blob/master/tasks/votes_house/votes_house.rb) with the `year=current` or `year=2016` flag should force the scraper to pick up all votes, not just the latest 20.

**Comment by dmc2015** [comment]
@clozano170 Thank you for bring this to our attention the information should be correct now. 
@konklone Thanks for the info
